services:
  rebot-7:
    image: ghcr.io/repryty/rebot-7
    volumes:
      - ./data:/usr/src/app/data
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
volumes:
  data: 